version: "3.7"
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - local-net

  app:
    links:
      - db
    build:
      context: ./app
      args:
        project_directory: "/app/"
    container_name: app
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    depends_on:
      - db
    networks:
      - local-net
    ports:
      - "5000:5000"
    command: "uwsgi --ini /app/uwsgi.ini"

  web:
    container_name: web-server
    hostname: web-server
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local-net

networks:
  local-net:
    driver: bridge